name: Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: docker://pandoc/latex:2.19
        with:
          args: >-
            --standalone
            -V geometry:margin=1in
            --output="public/Vitalii Makarchenkov.pdf"
            src/cv.md
      - uses: docker://pandoc/latex:2.19
        with:
          args: >-
            --standalone
            -V geometry:margin=1in
            --output="public/Vitalii Makarchenkov.docx"
            src/cv.md
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
